version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails_app
    environment:
      - RAILS_ENV=${RAILS_ENV}
    depends_on:
      - db
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"